# SPDX-FileCopyrightText: 2026 Formael
# SPDX-License-Identifier: Apache-2.0
#
# REUSE licensing for files that cannot carry an inline SPDX header (JSON, lockfiles, dotfiles,
# and prose without a header). Source files carry inline headers; those take precedence. Full
# `reuse lint` full wiring is deferred; this file covers static asset annotations only.

version = 1

[[annotations]]
path = [
  "package.json",
  "packages/**/package.json",
  "**/tsconfig*.json",
  "biome.json",
  ".changeset/config.json",
  "pnpm-workspace.yaml",
  "pnpm-lock.yaml",
  ".npmrc",
  ".gitignore",
  ".github/CODEOWNERS",
]
SPDX-FileCopyrightText = "2026 Formael"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  ".github/ISSUE_TEMPLATE/bug_report.md",
  ".github/ISSUE_TEMPLATE/feature_request.md",
]
SPDX-FileCopyrightText = "2026 Formael"
SPDX-License-Identifier = "Apache-2.0"
